name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # - name: Run unit tests
      #   run: go test ./...

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest ./app

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible
          ansible-galaxy collection install community.docker

      - name: Install cloudflared
        run: sudo apt-get install -y cloudflared
      - name: Run Ansible through Access tunnel
        run: |
          cloudflared access ssh --hostname ssh.alikazai.com \
            --id ${{ secrets.CF_ACCESS_CLIENT_ID }} \
            --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }} \
            --command "ansible-playbook ansible/playbook.yml ..."

      - name: Deploy via Ansible over Cloudflare SSH
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible_key
          chmod 600 ansible_key
          ansible-playbook ansible/playbook.yml \
            -i "${{ vars.SSH_HOST }}," \
            --user "${{ vars.SSH_USER }}" \
            --private-key ansible_key
